### ISSUE TITLE
Culture is not supported. (Parameter 'culture'). 8192 (0x2000) is an invalid culture identifier.

### ISSUE THREAD

**Issue by zspitz** [NuGetPackageExplorer/NuGetPackageExplorer#1052]
**Type**: Bug
**NPE version**: 5.7.98.0
**OS version**: Windows 10 Home 19041.329
**Installed from**: Microsoft Store

- What is the current result?

After choosing **Open package from online feed**, I get the following dialog:

![image](https://user-images.githubusercontent.com/312166/85976426-38360300-b9e3-11ea-8bb3-298ee7ec0118.png)

**Culture is not supported. (Parameter 'culture'). 8192 (0x2000) is an invalid culture identifier.**

After closing the dialog, the application quits.

- Is there a package on Nuget.org which shows the bug?

It doesn't appear related to a specific package.

**Comment by clairernovotny** [comment]
Do you know the locale settings for your computer? What language is it set to?

**Comment by zspitz** [comment]
English (Israel), I guess, based on **Settings** -> **Region**.

Is there somewhere I can find the precise information you're looking for?

**Comment by zspitz** [comment]
> After closing the dialog, the application quits.

More precisely, the application doesn't quit right away. But any further interaction with the UI (clicking on buttons, selecting from the package list, clicking on the search textbox, closing the online package selection window) and the entire application shuts down without any further message.

**Comment by clairernovotny** [comment]
Stack trace here: https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues/1057

This is likely a WPF issue and should be filed on dotnet/wpf.

**Comment by zspitz** [comment]
I installed .NET 5 Preview 7, and the issue has been resolved.

**Comment by jnyrup** [comment]
Hmm... upgrading to preview7 didn't resolve it for me.
I guess NugetPackageExplorer needs to be re-compiled with preview7 since it includes all the BCL libraries?

**Comment by zspitz** [comment]
@jnyrup I should also add that I downloaded the nightly build of NPE as well.

**Comment by jnyrup** [comment]
Ahh, of course.
I thought you meant upgrading to preview7 and running the latest NPE from https://github.com/nugetpackageexplorer/nugetpackageexplorer/releases
