### ISSUE TITLE
When manually editing Framework References via the Metadata xml editor it's possible to crash the applciation

### ISSUE THREAD

**Issue by mjjames** [NuGetPackageExplorer/NuGetPackageExplorer#722]
**Type** BUG
**NPE version**: (e.g. 5.x) (see Help -> about)
**OS version**:  Windows 10 1942

**Installed from**: Built from Source
- What is the current result?
If you manually edit the metadata xml and remove the name for a framework reference the application crashes.

- What is the expected result?
Validation / error message should be shown just like there is if you remove or mistype the targetFramework attribute

Screenshot of my example data:
![image](https://user-images.githubusercontent.com/514455/59556977-7ffb0f80-8fc5-11e9-8adf-12d0ea8a9dad.png)

**Comment by mjjames** [comment]
For completeness find below my comments I wrongly put on an issue that I thought was the same one:
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues/702#issuecomment-502403154

> when you manually edit the xml usually errors stop you from saving / continuing with bad data. For example if NuGet.Packaging.FrameworkReferenceGroup is missing its TargetFramework attribute you can't continue as the SaveMetadataAfterEditSource catches any exceptions thrown during the creation of EditablePackageMetadata.
> 
> However, NuGet.Packaging.FrameworkReferenceGroup has an IEnumerable of FrameworkReferences that are lazily evaluated due to LINQ. This means the usual mechanism of catching bad data doesn't kick in, then as soon as the WPF trys to bind the IEnumerable is evaluated and the exception is then thrown.
> 
> Weirdly, if you remove the name attribute from a package dependency you don't get an error (which you assume you would as its missing) instead the package entry is simply stripped from the collection. This points to inconsitencies in the NuGet.Packaging.Manifest class and how it handles bad data.
> 
> As this appears to be an issue in how the Manifest is parsed and also how its using lazy enumerations it's worth raising this in the NuGet repository. However is it worth trying to force the lazy evaluations as part of the SaveMetadataAfterEditSource method? It would feel a bit hacky, probably use the GetLastOrDefault() method Jon Skeet suggests, but it would ensure the app doesn't crash out on this or other issues of the same type.

https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues/702#issuecomment-502403425

> rather than sticking something like:
> 
> foreach (var group in source.FrameworkReferenceGroups) { _ = group.FrameworkReferences.LastOrDefault(); }
> 
> into the constructor of EditablePackageMetadata would it be more prudent to add a "Validate Package Source" method or an extension method on IPackageMetadata that can be appropriately called as part of SaveMetadataAfterEditSource?

**Comment by ivanbuha** [comment]
Hi @onovotny , @mjjames. 

I was able to recreate the issue when using NuGet.Packaging.dll 5.3.0-xprivate.60008. 

I was not able to recreate the issue when using locally built NuGet.Packaging.dll 5.3.0-preview 2 from [NuGet.Client](https://github.com/NuGet/NuGet.Client) repo. Editor throws validation error, see below:
<img width="630" alt="issue#722" src="https://user-images.githubusercontent.com/25520025/61812623-7ad18180-ae09-11e9-928e-cdf156602dc1.PNG">

**Comment by 304NotModified** [comment]
> I was able to recreate the issue when using NuGet.Packaging.dll 5.3.0-xprivate.60008.

> I was not able to recreate the issue when using locally built NuGet.Packaging.dll 5.3.0-preview 2 from NuGet.Client repo. Editor throws validation error, see below:

I think we could close this one? (for now?) @onovotny what do you think?

**Comment by onovotny** [comment]
Can we verify fixed in the latest (which uses 60011), based on later nuget code?

**Comment by campersau** [comment]
I can still reproduce the bug with `NuGet.Packaging.dll` version `5.03.0.60011`. (Which crashes the app if I continue debugging.)

![image](https://user-images.githubusercontent.com/4009570/62517797-6db08b80-b828-11e9-92bc-9ea83638c37c.png)
